# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/mainwindow.ui'
#
# Created: Wed Jun 25 19:23:04 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1216, 949)
        self.centralWidget = QtGui.QWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralWidget.sizePolicy().hasHeightForWidth())
        self.centralWidget.setSizePolicy(sizePolicy)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.gridLayout_6 = QtGui.QGridLayout(self.centralWidget)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.tabs_canvas = QtGui.QTabWidget(self.centralWidget)
        self.tabs_canvas.setTabsClosable(True)
        self.tabs_canvas.setMovable(True)
        self.tabs_canvas.setObjectName(_fromUtf8("tabs_canvas"))
        self.gridLayout_6.addWidget(self.tabs_canvas, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralWidget)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        MainWindow.setStatusBar(self.statusBar)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1216, 27))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menuFile = QtGui.QMenu(self.menuBar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuEdit = QtGui.QMenu(self.menuBar)
        self.menuEdit.setObjectName(_fromUtf8("menuEdit"))
        self.menuHelp = QtGui.QMenu(self.menuBar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        self.menuVCS = QtGui.QMenu(self.menuBar)
        self.menuVCS.setObjectName(_fromUtf8("menuVCS"))
        self.menuAttach_to_remote_repo = QtGui.QMenu(self.menuVCS)
        self.menuAttach_to_remote_repo.setObjectName(_fromUtf8("menuAttach_to_remote_repo"))
        self.menuView = QtGui.QMenu(self.menuBar)
        self.menuView.setObjectName(_fromUtf8("menuView"))
        MainWindow.setMenuBar(self.menuBar)
        self.dock_explorer = QtGui.QDockWidget(MainWindow)
        self.dock_explorer.setFeatures(QtGui.QDockWidget.DockWidgetFloatable|QtGui.QDockWidget.DockWidgetMovable)
        self.dock_explorer.setAllowedAreas(QtCore.Qt.LeftDockWidgetArea|QtCore.Qt.RightDockWidgetArea)
        self.dock_explorer.setWindowTitle(_fromUtf8(""))
        self.dock_explorer.setObjectName(_fromUtf8("dock_explorer"))
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.gridLayout = QtGui.QGridLayout(self.dockWidgetContents)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.tabs_dashboard_main = QtGui.QTabWidget(self.dockWidgetContents)
        self.tabs_dashboard_main.setTabPosition(QtGui.QTabWidget.West)
        self.tabs_dashboard_main.setObjectName(_fromUtf8("tabs_dashboard_main"))
        self.tab_commit_explorer = QtGui.QWidget()
        self.tab_commit_explorer.setObjectName(_fromUtf8("tab_commit_explorer"))
        self.gridLayout_9 = QtGui.QGridLayout(self.tab_commit_explorer)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.splitter_5 = QtGui.QSplitter(self.tab_commit_explorer)
        self.splitter_5.setOrientation(QtCore.Qt.Vertical)
        self.splitter_5.setChildrenCollapsible(False)
        self.splitter_5.setObjectName(_fromUtf8("splitter_5"))
        self.splitter_4 = QtGui.QSplitter(self.splitter_5)
        self.splitter_4.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_4.setChildrenCollapsible(False)
        self.splitter_4.setObjectName(_fromUtf8("splitter_4"))
        self.tabs_file_directory = QtGui.QTabWidget(self.splitter_4)
        self.tabs_file_directory.setObjectName(_fromUtf8("tabs_file_directory"))
        self.tab_commit_tree = QtGui.QWidget()
        self.tab_commit_tree.setObjectName(_fromUtf8("tab_commit_tree"))
        self.gridLayout_3 = QtGui.QGridLayout(self.tab_commit_tree)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.tree_commit_tree = QtGui.QTreeView(self.tab_commit_tree)
        self.tree_commit_tree.setObjectName(_fromUtf8("tree_commit_tree"))
        self.gridLayout_3.addWidget(self.tree_commit_tree, 0, 0, 1, 1)
        self.tabs_file_directory.addTab(self.tab_commit_tree, _fromUtf8(""))
        self.tab_commit_patch = QtGui.QWidget()
        self.tab_commit_patch.setObjectName(_fromUtf8("tab_commit_patch"))
        self.gridLayout_2 = QtGui.QGridLayout(self.tab_commit_patch)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.tree_commit_patch = QtGui.QTreeView(self.tab_commit_patch)
        self.tree_commit_patch.setObjectName(_fromUtf8("tree_commit_patch"))
        self.gridLayout_2.addWidget(self.tree_commit_patch, 0, 0, 1, 1)
        self.tabs_file_directory.addTab(self.tab_commit_patch, _fromUtf8(""))
        self.layoutWidget = QtGui.QWidget(self.splitter_4)
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.layout_commit_details = QtGui.QVBoxLayout(self.layoutWidget)
        self.layout_commit_details.setMargin(0)
        self.layout_commit_details.setObjectName(_fromUtf8("layout_commit_details"))
        self.lbl_commit_details_header = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_commit_details_header.sizePolicy().hasHeightForWidth())
        self.lbl_commit_details_header.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setUnderline(False)
        self.lbl_commit_details_header.setFont(font)
        self.lbl_commit_details_header.setObjectName(_fromUtf8("lbl_commit_details_header"))
        self.layout_commit_details.addWidget(self.lbl_commit_details_header)
        self.scrollArea = QtGui.QScrollArea(self.layoutWidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 350, 505))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.gridLayout_8 = QtGui.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.gridLayout_7 = QtGui.QGridLayout()
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.lbl_commit_msg_header = QtGui.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_commit_msg_header.sizePolicy().hasHeightForWidth())
        self.lbl_commit_msg_header.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_commit_msg_header.setFont(font)
        self.lbl_commit_msg_header.setObjectName(_fromUtf8("lbl_commit_msg_header"))
        self.gridLayout_7.addWidget(self.lbl_commit_msg_header, 0, 0, 1, 2)
        self.lbl_commit_sha = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.lbl_commit_sha.setObjectName(_fromUtf8("lbl_commit_sha"))
        self.gridLayout_7.addWidget(self.lbl_commit_sha, 1, 0, 1, 1)
        self.txt_commit_sha = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.txt_commit_sha.setMaxLength(40)
        self.txt_commit_sha.setReadOnly(True)
        self.txt_commit_sha.setObjectName(_fromUtf8("txt_commit_sha"))
        self.gridLayout_7.addWidget(self.txt_commit_sha, 1, 1, 1, 1)
        self.lbl_commit_author = QtGui.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lbl_commit_author.setFont(font)
        self.lbl_commit_author.setObjectName(_fromUtf8("lbl_commit_author"))
        self.gridLayout_7.addWidget(self.lbl_commit_author, 2, 0, 1, 1)
        self.splitter = QtGui.QSplitter(self.scrollAreaWidgetContents)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.layoutWidget1 = QtGui.QWidget(self.splitter)
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.txt_author_name = QtGui.QLineEdit(self.layoutWidget1)
        self.txt_author_name.setReadOnly(True)
        self.txt_author_name.setObjectName(_fromUtf8("txt_author_name"))
        self.verticalLayout_2.addWidget(self.txt_author_name)
        self.txt_author_email = QtGui.QLineEdit(self.layoutWidget1)
        self.txt_author_email.setReadOnly(True)
        self.txt_author_email.setObjectName(_fromUtf8("txt_author_email"))
        self.verticalLayout_2.addWidget(self.txt_author_email)
        self.layoutWidget2 = QtGui.QWidget(self.splitter)
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.txt_author_date = QtGui.QLineEdit(self.layoutWidget2)
        self.txt_author_date.setMaximumSize(QtCore.QSize(130, 16777215))
        self.txt_author_date.setBaseSize(QtCore.QSize(0, 0))
        self.txt_author_date.setReadOnly(True)
        self.txt_author_date.setObjectName(_fromUtf8("txt_author_date"))
        self.verticalLayout.addWidget(self.txt_author_date)
        self.txt_author_time = QtGui.QLineEdit(self.layoutWidget2)
        self.txt_author_time.setMaximumSize(QtCore.QSize(130, 16777215))
        self.txt_author_time.setReadOnly(True)
        self.txt_author_time.setObjectName(_fromUtf8("txt_author_time"))
        self.verticalLayout.addWidget(self.txt_author_time)
        self.gridLayout_7.addWidget(self.splitter, 3, 0, 1, 2)
        self.lbl_commit_committer = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.lbl_commit_committer.setObjectName(_fromUtf8("lbl_commit_committer"))
        self.gridLayout_7.addWidget(self.lbl_commit_committer, 4, 0, 1, 1)
        self.splitter_2 = QtGui.QSplitter(self.scrollAreaWidgetContents)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName(_fromUtf8("splitter_2"))
        self.layoutWidget_4 = QtGui.QWidget(self.splitter_2)
        self.layoutWidget_4.setObjectName(_fromUtf8("layoutWidget_4"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.layoutWidget_4)
        self.verticalLayout_6.setMargin(0)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.txt_author_name_3 = QtGui.QLineEdit(self.layoutWidget_4)
        self.txt_author_name_3.setReadOnly(True)
        self.txt_author_name_3.setObjectName(_fromUtf8("txt_author_name_3"))
        self.verticalLayout_6.addWidget(self.txt_author_name_3)
        self.txt_author_email_3 = QtGui.QLineEdit(self.layoutWidget_4)
        self.txt_author_email_3.setReadOnly(True)
        self.txt_author_email_3.setObjectName(_fromUtf8("txt_author_email_3"))
        self.verticalLayout_6.addWidget(self.txt_author_email_3)
        self.layoutWidget_3 = QtGui.QWidget(self.splitter_2)
        self.layoutWidget_3.setObjectName(_fromUtf8("layoutWidget_3"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.layoutWidget_3)
        self.verticalLayout_5.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.verticalLayout_5.setMargin(0)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.txt_author_date_3 = QtGui.QLineEdit(self.layoutWidget_3)
        self.txt_author_date_3.setMaximumSize(QtCore.QSize(130, 16777215))
        self.txt_author_date_3.setReadOnly(True)
        self.txt_author_date_3.setObjectName(_fromUtf8("txt_author_date_3"))
        self.verticalLayout_5.addWidget(self.txt_author_date_3)
        self.txt_author_time_3 = QtGui.QLineEdit(self.layoutWidget_3)
        self.txt_author_time_3.setMaximumSize(QtCore.QSize(130, 16777215))
        self.txt_author_time_3.setReadOnly(True)
        self.txt_author_time_3.setObjectName(_fromUtf8("txt_author_time_3"))
        self.verticalLayout_5.addWidget(self.txt_author_time_3)
        self.gridLayout_7.addWidget(self.splitter_2, 5, 0, 1, 2)
        self.lbl_commit_parents = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.lbl_commit_parents.setObjectName(_fromUtf8("lbl_commit_parents"))
        self.gridLayout_7.addWidget(self.lbl_commit_parents, 6, 0, 1, 1)
        self.table_parents = QtGui.QTableView(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.table_parents.sizePolicy().hasHeightForWidth())
        self.table_parents.setSizePolicy(sizePolicy)
        self.table_parents.setMinimumSize(QtCore.QSize(0, 30))
        self.table_parents.setMaximumSize(QtCore.QSize(16777215, 30))
        self.table_parents.setObjectName(_fromUtf8("table_parents"))
        self.gridLayout_7.addWidget(self.table_parents, 6, 1, 1, 1)
        self.lbl_commt_children = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.lbl_commt_children.setObjectName(_fromUtf8("lbl_commt_children"))
        self.gridLayout_7.addWidget(self.lbl_commt_children, 7, 0, 1, 1)
        self.table_children = QtGui.QTableView(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.table_children.sizePolicy().hasHeightForWidth())
        self.table_children.setSizePolicy(sizePolicy)
        self.table_children.setMinimumSize(QtCore.QSize(0, 30))
        self.table_children.setMaximumSize(QtCore.QSize(16777215, 30))
        self.table_children.setObjectName(_fromUtf8("table_children"))
        self.gridLayout_7.addWidget(self.table_children, 7, 1, 1, 1)
        self.lbl_commit_branches = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.lbl_commit_branches.setObjectName(_fromUtf8("lbl_commit_branches"))
        self.gridLayout_7.addWidget(self.lbl_commit_branches, 8, 0, 1, 1)
        self.list_branches = QtGui.QListView(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.list_branches.sizePolicy().hasHeightForWidth())
        self.list_branches.setSizePolicy(sizePolicy)
        self.list_branches.setMinimumSize(QtCore.QSize(0, 30))
        self.list_branches.setMaximumSize(QtCore.QSize(16777215, 30))
        self.list_branches.setObjectName(_fromUtf8("list_branches"))
        self.gridLayout_7.addWidget(self.list_branches, 8, 1, 1, 1)
        self.txt_commit_msg = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_commit_msg.sizePolicy().hasHeightForWidth())
        self.txt_commit_msg.setSizePolicy(sizePolicy)
        self.txt_commit_msg.setMinimumSize(QtCore.QSize(0, 80))
        self.txt_commit_msg.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.txt_commit_msg.setFont(font)
        self.txt_commit_msg.setObjectName(_fromUtf8("txt_commit_msg"))
        self.gridLayout_7.addWidget(self.txt_commit_msg, 9, 0, 1, 2)
        self.gridLayout_8.addLayout(self.gridLayout_7, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.layout_commit_details.addWidget(self.scrollArea)
        self.tabs_dashboard_helper = QtGui.QTabWidget(self.splitter_5)
        self.tabs_dashboard_helper.setMinimumSize(QtCore.QSize(0, 120))
        self.tabs_dashboard_helper.setTabPosition(QtGui.QTabWidget.South)
        self.tabs_dashboard_helper.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabs_dashboard_helper.setObjectName(_fromUtf8("tabs_dashboard_helper"))
        self.tab_file_viewer = QtGui.QWidget()
        self.tab_file_viewer.setObjectName(_fromUtf8("tab_file_viewer"))
        self.gridLayout_4 = QtGui.QGridLayout(self.tab_file_viewer)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.txt_file_viewer = QtGui.QTextBrowser(self.tab_file_viewer)
        self.txt_file_viewer.setObjectName(_fromUtf8("txt_file_viewer"))
        self.gridLayout_4.addWidget(self.txt_file_viewer, 0, 0, 1, 1)
        self.tabs_dashboard_helper.addTab(self.tab_file_viewer, _fromUtf8(""))
        self.tab_branches = QtGui.QWidget()
        self.tab_branches.setObjectName(_fromUtf8("tab_branches"))
        self.tabs_dashboard_helper.addTab(self.tab_branches, _fromUtf8(""))
        self.tab_tags = QtGui.QWidget()
        self.tab_tags.setObjectName(_fromUtf8("tab_tags"))
        self.tabs_dashboard_helper.addTab(self.tab_tags, _fromUtf8(""))
        self.gridLayout_9.addWidget(self.splitter_5, 0, 0, 1, 1)
        self.tabs_dashboard_main.addTab(self.tab_commit_explorer, _fromUtf8(""))
        self.tab_command_explorer = QtGui.QWidget()
        self.tab_command_explorer.setObjectName(_fromUtf8("tab_command_explorer"))
        self.gridLayout_13 = QtGui.QGridLayout(self.tab_command_explorer)
        self.gridLayout_13.setObjectName(_fromUtf8("gridLayout_13"))
        self.splitter_3 = QtGui.QSplitter(self.tab_command_explorer)
        self.splitter_3.setOrientation(QtCore.Qt.Vertical)
        self.splitter_3.setChildrenCollapsible(False)
        self.splitter_3.setObjectName(_fromUtf8("splitter_3"))
        self.layoutWidget3 = QtGui.QWidget(self.splitter_3)
        self.layoutWidget3.setObjectName(_fromUtf8("layoutWidget3"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.gridLayout_12 = QtGui.QGridLayout()
        self.gridLayout_12.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.scrollArea_3 = QtGui.QScrollArea(self.layoutWidget3)
        self.scrollArea_3.setMinimumSize(QtCore.QSize(180, 0))
        self.scrollArea_3.setMaximumSize(QtCore.QSize(180, 16777215))
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName(_fromUtf8("scrollArea_3"))
        self.scrollAreaWidgetContents_3 = QtGui.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 165, 638))
        self.scrollAreaWidgetContents_3.setObjectName(_fromUtf8("scrollAreaWidgetContents_3"))
        self.gridLayout_11 = QtGui.QGridLayout(self.scrollAreaWidgetContents_3)
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.btn_command_init = QtGui.QPushButton(self.scrollAreaWidgetContents_3)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_command_init.setFont(font)
        self.btn_command_init.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.btn_command_init.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_command_init.setStyleSheet(_fromUtf8("Text-align:left; padding: 6px; padding-left: 12px;"))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/add.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_command_init.setIcon(icon)
        self.btn_command_init.setFlat(False)
        self.btn_command_init.setObjectName(_fromUtf8("btn_command_init"))
        self.verticalLayout_7.addWidget(self.btn_command_init)
        self.btn_command_init_2 = QtGui.QPushButton(self.scrollAreaWidgetContents_3)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_command_init_2.setFont(font)
        self.btn_command_init_2.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.btn_command_init_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_command_init_2.setStyleSheet(_fromUtf8("Text-align:left; padding: 6px; padding-left: 12px;"))
        self.btn_command_init_2.setIcon(icon)
        self.btn_command_init_2.setFlat(False)
        self.btn_command_init_2.setObjectName(_fromUtf8("btn_command_init_2"))
        self.verticalLayout_7.addWidget(self.btn_command_init_2)
        self.btn_command_init_6 = QtGui.QPushButton(self.scrollAreaWidgetContents_3)
        self.btn_command_init_6.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_command_init_6.setFont(font)
        self.btn_command_init_6.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.btn_command_init_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_command_init_6.setStyleSheet(_fromUtf8("Text-align:left; padding: 6px; padding-left: 12px;"))
        self.btn_command_init_6.setIcon(icon)
        self.btn_command_init_6.setFlat(False)
        self.btn_command_init_6.setObjectName(_fromUtf8("btn_command_init_6"))
        self.verticalLayout_7.addWidget(self.btn_command_init_6)
        self.btn_command_init_3 = QtGui.QPushButton(self.scrollAreaWidgetContents_3)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_command_init_3.setFont(font)
        self.btn_command_init_3.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.btn_command_init_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_command_init_3.setStyleSheet(_fromUtf8("Text-align:left; padding: 6px; padding-left: 12px;"))
        self.btn_command_init_3.setIcon(icon)
        self.btn_command_init_3.setFlat(False)
        self.btn_command_init_3.setObjectName(_fromUtf8("btn_command_init_3"))
        self.verticalLayout_7.addWidget(self.btn_command_init_3)
        self.btn_command_init_4 = QtGui.QPushButton(self.scrollAreaWidgetContents_3)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_command_init_4.setFont(font)
        self.btn_command_init_4.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.btn_command_init_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_command_init_4.setStyleSheet(_fromUtf8("Text-align:left; padding: 6px; padding-left: 12px;"))
        self.btn_command_init_4.setIcon(icon)
        self.btn_command_init_4.setFlat(False)
        self.btn_command_init_4.setObjectName(_fromUtf8("btn_command_init_4"))
        self.verticalLayout_7.addWidget(self.btn_command_init_4)
        self.btn_command_init_5 = QtGui.QPushButton(self.scrollAreaWidgetContents_3)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_command_init_5.setFont(font)
        self.btn_command_init_5.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.btn_command_init_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_command_init_5.setStyleSheet(_fromUtf8("Text-align:left; padding: 6px; padding-left: 12px;"))
        self.btn_command_init_5.setIcon(icon)
        self.btn_command_init_5.setFlat(False)
        self.btn_command_init_5.setObjectName(_fromUtf8("btn_command_init_5"))
        self.verticalLayout_7.addWidget(self.btn_command_init_5)
        self.btn_command_init_7 = QtGui.QPushButton(self.scrollAreaWidgetContents_3)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_command_init_7.setFont(font)
        self.btn_command_init_7.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.btn_command_init_7.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_command_init_7.setStyleSheet(_fromUtf8("Text-align:left; padding: 6px; padding-left: 12px;"))
        self.btn_command_init_7.setIcon(icon)
        self.btn_command_init_7.setFlat(False)
        self.btn_command_init_7.setObjectName(_fromUtf8("btn_command_init_7"))
        self.verticalLayout_7.addWidget(self.btn_command_init_7)
        self.btn_command_init_9 = QtGui.QPushButton(self.scrollAreaWidgetContents_3)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_command_init_9.setFont(font)
        self.btn_command_init_9.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.btn_command_init_9.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_command_init_9.setStyleSheet(_fromUtf8("Text-align:left; padding: 6px; padding-left: 12px;"))
        self.btn_command_init_9.setIcon(icon)
        self.btn_command_init_9.setFlat(False)
        self.btn_command_init_9.setObjectName(_fromUtf8("btn_command_init_9"))
        self.verticalLayout_7.addWidget(self.btn_command_init_9)
        self.btn_command_init_11 = QtGui.QPushButton(self.scrollAreaWidgetContents_3)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_command_init_11.setFont(font)
        self.btn_command_init_11.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.btn_command_init_11.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_command_init_11.setStyleSheet(_fromUtf8("Text-align:left; padding: 6px; padding-left: 12px;"))
        self.btn_command_init_11.setIcon(icon)
        self.btn_command_init_11.setFlat(False)
        self.btn_command_init_11.setObjectName(_fromUtf8("btn_command_init_11"))
        self.verticalLayout_7.addWidget(self.btn_command_init_11)
        self.btn_command_init_8 = QtGui.QPushButton(self.scrollAreaWidgetContents_3)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_command_init_8.setFont(font)
        self.btn_command_init_8.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.btn_command_init_8.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_command_init_8.setStyleSheet(_fromUtf8("Text-align:left; padding: 6px; padding-left: 12px;"))
        self.btn_command_init_8.setIcon(icon)
        self.btn_command_init_8.setFlat(False)
        self.btn_command_init_8.setObjectName(_fromUtf8("btn_command_init_8"))
        self.verticalLayout_7.addWidget(self.btn_command_init_8)
        self.btn_command_init_10 = QtGui.QPushButton(self.scrollAreaWidgetContents_3)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_command_init_10.setFont(font)
        self.btn_command_init_10.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.btn_command_init_10.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_command_init_10.setStyleSheet(_fromUtf8("Text-align:left; padding: 6px; padding-left: 12px;"))
        self.btn_command_init_10.setIcon(icon)
        self.btn_command_init_10.setFlat(False)
        self.btn_command_init_10.setObjectName(_fromUtf8("btn_command_init_10"))
        self.verticalLayout_7.addWidget(self.btn_command_init_10)
        self.btn_command_init_12 = QtGui.QPushButton(self.scrollAreaWidgetContents_3)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_command_init_12.setFont(font)
        self.btn_command_init_12.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.btn_command_init_12.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_command_init_12.setStyleSheet(_fromUtf8("Text-align:left; padding: 6px; padding-left: 12px;"))
        self.btn_command_init_12.setIcon(icon)
        self.btn_command_init_12.setFlat(False)
        self.btn_command_init_12.setObjectName(_fromUtf8("btn_command_init_12"))
        self.verticalLayout_7.addWidget(self.btn_command_init_12)
        self.btn_command_init_13 = QtGui.QPushButton(self.scrollAreaWidgetContents_3)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_command_init_13.setFont(font)
        self.btn_command_init_13.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.btn_command_init_13.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_command_init_13.setStyleSheet(_fromUtf8("Text-align:left; padding: 6px; padding-left: 12px;"))
        self.btn_command_init_13.setIcon(icon)
        self.btn_command_init_13.setFlat(False)
        self.btn_command_init_13.setObjectName(_fromUtf8("btn_command_init_13"))
        self.verticalLayout_7.addWidget(self.btn_command_init_13)
        self.gridLayout_11.addLayout(self.verticalLayout_7, 0, 0, 1, 1)
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_3)
        self.gridLayout_12.addWidget(self.scrollArea_3, 0, 0, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout_12)
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.gridLayout_10 = QtGui.QGridLayout()
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.scrollArea_2 = QtGui.QScrollArea(self.layoutWidget3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea_2.sizePolicy().hasHeightForWidth())
        self.scrollArea_2.setSizePolicy(sizePolicy)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName(_fromUtf8("scrollArea_2"))
        self.scrollAreaWidgetContents_2 = QtGui.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 308, 507))
        self.scrollAreaWidgetContents_2.setObjectName(_fromUtf8("scrollAreaWidgetContents_2"))
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.gridLayout_10.addWidget(self.scrollArea_2, 1, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_10.addWidget(self.label_4, 0, 0, 1, 1)
        self.verticalLayout_8.addLayout(self.gridLayout_10)
        self.horizontalLayout.addLayout(self.verticalLayout_8)
        self.layoutWidget4 = QtGui.QWidget(self.splitter_3)
        self.layoutWidget4.setObjectName(_fromUtf8("layoutWidget4"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.layoutWidget4)
        self.verticalLayout_9.setMargin(0)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.label_3 = QtGui.QLabel(self.layoutWidget4)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_9.addWidget(self.label_3)
        self.textBrowser = QtGui.QTextBrowser(self.layoutWidget4)
        self.textBrowser.setObjectName(_fromUtf8("textBrowser"))
        self.verticalLayout_9.addWidget(self.textBrowser)
        self.gridLayout_13.addWidget(self.splitter_3, 0, 0, 1, 1)
        self.tabs_dashboard_main.addTab(self.tab_command_explorer, _fromUtf8(""))
        self.gridLayout.addWidget(self.tabs_dashboard_main, 0, 0, 1, 1)
        self.dock_explorer.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dock_explorer)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        MainWindow.insertToolBarBreak(self.toolBar)
        self.action_open = QtGui.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/open_repo.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_open.setIcon(icon1)
        self.action_open.setObjectName(_fromUtf8("action_open"))
        self.action_git_init = QtGui.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/init.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_git_init.setIcon(icon2)
        self.action_git_init.setObjectName(_fromUtf8("action_git_init"))
        self.actionGitAdd = QtGui.QAction(MainWindow)
        self.actionGitAdd.setIcon(icon)
        self.actionGitAdd.setObjectName(_fromUtf8("actionGitAdd"))
        self.actionGitMerge = QtGui.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/merge.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionGitMerge.setIcon(icon3)
        self.actionGitMerge.setObjectName(_fromUtf8("actionGitMerge"))
        self.actionGitCommit = QtGui.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/commit.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionGitCommit.setIcon(icon4)
        self.actionGitCommit.setObjectName(_fromUtf8("actionGitCommit"))
        self.actionGitBranch = QtGui.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/Branch")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionGitBranch.setIcon(icon5)
        self.actionGitBranch.setObjectName(_fromUtf8("actionGitBranch"))
        self.actionGit_Init = QtGui.QAction(MainWindow)
        self.actionGit_Init.setObjectName(_fromUtf8("actionGit_Init"))
        self.actionGit_Add = QtGui.QAction(MainWindow)
        self.actionGit_Add.setObjectName(_fromUtf8("actionGit_Add"))
        self.actionGit_Commit = QtGui.QAction(MainWindow)
        self.actionGit_Commit.setObjectName(_fromUtf8("actionGit_Commit"))
        self.actionGit_Merge = QtGui.QAction(MainWindow)
        self.actionGit_Merge.setObjectName(_fromUtf8("actionGit_Merge"))
        self.actionGit_Branch = QtGui.QAction(MainWindow)
        self.actionGit_Branch.setObjectName(_fromUtf8("actionGit_Branch"))
        self.actionCurrent_Version = QtGui.QAction(MainWindow)
        self.actionCurrent_Version.setObjectName(_fromUtf8("actionCurrent_Version"))
        self.actionAbout_us = QtGui.QAction(MainWindow)
        self.actionAbout_us.setObjectName(_fromUtf8("actionAbout_us"))
        self.actionGitRevert = QtGui.QAction(MainWindow)
        self.actionGitRevert.setEnabled(False)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/revert.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionGitRevert.setIcon(icon6)
        self.actionGitRevert.setObjectName(_fromUtf8("actionGitRevert"))
        self.actionGitHub = QtGui.QAction(MainWindow)
        self.actionGitHub.setObjectName(_fromUtf8("actionGitHub"))
        self.actionBitBucket = QtGui.QAction(MainWindow)
        self.actionBitBucket.setObjectName(_fromUtf8("actionBitBucket"))
        self.actionGit_Revert = QtGui.QAction(MainWindow)
        self.actionGit_Revert.setEnabled(False)
        self.actionGit_Revert.setObjectName(_fromUtf8("actionGit_Revert"))
        self.actionGitPush = QtGui.QAction(MainWindow)
        self.actionGitPush.setEnabled(False)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/push.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionGitPush.setIcon(icon7)
        self.actionGitPush.setObjectName(_fromUtf8("actionGitPush"))
        self.actionGitPull = QtGui.QAction(MainWindow)
        self.actionGitPull.setEnabled(False)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/pull.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionGitPull.setIcon(icon8)
        self.actionGitPull.setObjectName(_fromUtf8("actionGitPull"))
        self.actionGit_Push = QtGui.QAction(MainWindow)
        self.actionGit_Push.setEnabled(False)
        self.actionGit_Push.setObjectName(_fromUtf8("actionGit_Push"))
        self.actionGit_Pull = QtGui.QAction(MainWindow)
        self.actionGit_Pull.setEnabled(False)
        self.actionGit_Pull.setObjectName(_fromUtf8("actionGit_Pull"))
        self.actionRefresh = QtGui.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/refresh.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRefresh.setIcon(icon9)
        self.actionRefresh.setObjectName(_fromUtf8("actionRefresh"))
        self.actionOpenRepo = QtGui.QAction(MainWindow)
        self.actionOpenRepo.setIcon(icon1)
        self.actionOpenRepo.setObjectName(_fromUtf8("actionOpenRepo"))
        self.actionGitCheckout = QtGui.QAction(MainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/checkout_branch.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionGitCheckout.setIcon(icon10)
        self.actionGitCheckout.setObjectName(_fromUtf8("actionGitCheckout"))
        self.menuFile.addAction(self.action_open)
        self.menuHelp.addAction(self.actionCurrent_Version)
        self.menuHelp.addAction(self.actionAbout_us)
        self.menuAttach_to_remote_repo.addAction(self.actionGitHub)
        self.menuAttach_to_remote_repo.addAction(self.actionBitBucket)
        self.menuVCS.addAction(self.menuAttach_to_remote_repo.menuAction())
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuEdit.menuAction())
        self.menuBar.addAction(self.menuView.menuAction())
        self.menuBar.addAction(self.menuVCS.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())
        self.toolBar.addAction(self.action_open)

        self.retranslateUi(MainWindow)
        self.tabs_canvas.setCurrentIndex(-1)
        self.tabs_dashboard_main.setCurrentIndex(0)
        self.tabs_file_directory.setCurrentIndex(0)
        self.tabs_dashboard_helper.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit", None))
        self.menuHelp.setTitle(_translate("MainWindow", "Help", None))
        self.menuVCS.setTitle(_translate("MainWindow", "VCS", None))
        self.menuAttach_to_remote_repo.setTitle(_translate("MainWindow", "Attach to remote repo", None))
        self.menuView.setTitle(_translate("MainWindow", "View", None))
        self.tabs_file_directory.setTabText(self.tabs_file_directory.indexOf(self.tab_commit_tree), _translate("MainWindow", "Tree", None))
        self.tabs_file_directory.setTabText(self.tabs_file_directory.indexOf(self.tab_commit_patch), _translate("MainWindow", "Patch", None))
        self.lbl_commit_details_header.setText(_translate("MainWindow", "Commit Details", None))
        self.lbl_commit_msg_header.setText(_translate("MainWindow", "Commit message header", None))
        self.lbl_commit_sha.setText(_translate("MainWindow", "SHA-1 ID", None))
        self.lbl_commit_author.setText(_translate("MainWindow", "Author", None))
        self.txt_author_name.setPlaceholderText(_translate("MainWindow", "Author Name", None))
        self.txt_author_email.setPlaceholderText(_translate("MainWindow", "Author Email", None))
        self.txt_author_date.setPlaceholderText(_translate("MainWindow", "Authored Date", None))
        self.txt_author_time.setPlaceholderText(_translate("MainWindow", "Authored Time", None))
        self.lbl_commit_committer.setText(_translate("MainWindow", "Committer", None))
        self.txt_author_name_3.setPlaceholderText(_translate("MainWindow", "Committer Name", None))
        self.txt_author_email_3.setPlaceholderText(_translate("MainWindow", "Committer Email", None))
        self.txt_author_date_3.setPlaceholderText(_translate("MainWindow", "Commit Date", None))
        self.txt_author_time_3.setPlaceholderText(_translate("MainWindow", "Commit Time", None))
        self.lbl_commit_parents.setText(_translate("MainWindow", "Parents", None))
        self.lbl_commt_children.setText(_translate("MainWindow", "Children", None))
        self.lbl_commit_branches.setText(_translate("MainWindow", "Branches", None))
        self.tabs_dashboard_helper.setTabText(self.tabs_dashboard_helper.indexOf(self.tab_file_viewer), _translate("MainWindow", "File Viewer", None))
        self.tabs_dashboard_helper.setTabText(self.tabs_dashboard_helper.indexOf(self.tab_branches), _translate("MainWindow", "Branches", None))
        self.tabs_dashboard_helper.setTabText(self.tabs_dashboard_helper.indexOf(self.tab_tags), _translate("MainWindow", "Tags", None))
        self.tabs_dashboard_main.setTabText(self.tabs_dashboard_main.indexOf(self.tab_commit_explorer), _translate("MainWindow", "Commits", None))
        self.btn_command_init.setText(_translate("MainWindow", "Init", None))
        self.btn_command_init_2.setText(_translate("MainWindow", "Clone", None))
        self.btn_command_init_6.setText(_translate("MainWindow", "Add", None))
        self.btn_command_init_3.setText(_translate("MainWindow", "Commit", None))
        self.btn_command_init_4.setText(_translate("MainWindow", "Branch", None))
        self.btn_command_init_5.setText(_translate("MainWindow", "Checkout", None))
        self.btn_command_init_7.setText(_translate("MainWindow", "Stash", None))
        self.btn_command_init_9.setText(_translate("MainWindow", "Merge", None))
        self.btn_command_init_11.setText(_translate("MainWindow", "Rebase", None))
        self.btn_command_init_8.setText(_translate("MainWindow", "Log", None))
        self.btn_command_init_10.setText(_translate("MainWindow", "Show", None))
        self.btn_command_init_12.setText(_translate("MainWindow", "Diff", None))
        self.btn_command_init_13.setText(_translate("MainWindow", "Status", None))
        self.label_4.setText(_translate("MainWindow", "Branch Options", None))
        self.label_3.setText(_translate("MainWindow", "Output", None))
        self.tabs_dashboard_main.setTabText(self.tabs_dashboard_main.indexOf(self.tab_command_explorer), _translate("MainWindow", "Commands", None))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar", None))
        self.action_open.setText(_translate("MainWindow", "Open", None))
        self.action_open.setToolTip(_translate("MainWindow", "Open a git repository", None))
        self.action_open.setStatusTip(_translate("MainWindow", "Open a git repository", None))
        self.action_git_init.setText(_translate("MainWindow", "Git Init", None))
        self.action_git_init.setToolTip(_translate("MainWindow", "Initialize a new Git repository", None))
        self.actionGitAdd.setText(_translate("MainWindow", "GitAdd", None))
        self.actionGitAdd.setToolTip(_translate("MainWindow", "Add some sweet files to your git repo", None))
        self.actionGitMerge.setText(_translate("MainWindow", "GitMerge", None))
        self.actionGitMerge.setToolTip(_translate("MainWindow", "Merges branches", None))
        self.actionGitCommit.setText(_translate("MainWindow", "GitCommit", None))
        self.actionGitCommit.setToolTip(_translate("MainWindow", "Commits", None))
        self.actionGitBranch.setText(_translate("MainWindow", "GitBranch", None))
        self.actionGitBranch.setToolTip(_translate("MainWindow", "Create a new branch from the current branch", None))
        self.actionGit_Init.setText(_translate("MainWindow", "Git Init", None))
        self.actionGit_Add.setText(_translate("MainWindow", "Git Add", None))
        self.actionGit_Commit.setText(_translate("MainWindow", "Git Commit", None))
        self.actionGit_Merge.setText(_translate("MainWindow", "Git Merge", None))
        self.actionGit_Branch.setText(_translate("MainWindow", "Git Branch", None))
        self.actionCurrent_Version.setText(_translate("MainWindow", "Current Version", None))
        self.actionAbout_us.setText(_translate("MainWindow", "About us", None))
        self.actionGitRevert.setText(_translate("MainWindow", "GitRevert", None))
        self.actionGitRevert.setToolTip(_translate("MainWindow", "Not implemented in this version. Sorry!", None))
        self.actionGitHub.setText(_translate("MainWindow", "GitHub", None))
        self.actionBitBucket.setText(_translate("MainWindow", "BitBucket", None))
        self.actionGit_Revert.setText(_translate("MainWindow", "Git Revert", None))
        self.actionGitPush.setText(_translate("MainWindow", "Gitpush", None))
        self.actionGitPush.setToolTip(_translate("MainWindow", "Not implemented in this version. Sorry!", None))
        self.actionGitPull.setText(_translate("MainWindow", "GitPull", None))
        self.actionGitPull.setToolTip(_translate("MainWindow", "Not implemented in this version. Sorry!", None))
        self.actionGit_Push.setText(_translate("MainWindow", "Git Push", None))
        self.actionGit_Pull.setText(_translate("MainWindow", "Git Pull", None))
        self.actionRefresh.setText(_translate("MainWindow", "Refresh", None))
        self.actionRefresh.setToolTip(_translate("MainWindow", "So Refreshing!", None))
        self.actionOpenRepo.setText(_translate("MainWindow", "OpenRepo", None))
        self.actionOpenRepo.setToolTip(_translate("MainWindow", "Open a repository", None))
        self.actionOpenRepo.setShortcut(_translate("MainWindow", "Ctrl+O", None))
        self.actionGitCheckout.setText(_translate("MainWindow", "GitCheckout", None))
        self.actionGitCheckout.setToolTip(_translate("MainWindow", "Checkout a different branch", None))

import images_rc

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

